/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface dspConstants {
  public final static int VOLUMEINDBTABLE = 121;
  public final static int MAXVOLSTEP = 30+1;
}
